// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quote_genarator.Data;

#nullable disable

namespace Quote_genarator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312052012_RemoveCategory")]
    partial class RemoveCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quote_genarator.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Quotes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Steve Jobs",
                            CreatedAt = new DateTime(2026, 3, 12, 5, 20, 12, 343, DateTimeKind.Utc).AddTicks(8403),
                            Text = "Stay hungry, stay foolish."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Albert Einstein",
                            CreatedAt = new DateTime(2026, 3, 12, 5, 20, 12, 343, DateTimeKind.Utc).AddTicks(8406),
                            Text = "Imagination is more important than knowledge."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Bruce Lee",
                            CreatedAt = new DateTime(2026, 3, 12, 5, 20, 12, 343, DateTimeKind.Utc).AddTicks(8407),
                            Text = "Be water, my friend."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Yoda",
                            CreatedAt = new DateTime(2026, 3, 12, 5, 20, 12, 343, DateTimeKind.Utc).AddTicks(8408),
                            Text = "Do or do not, there is no try."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
